---
mongo:
  image: mongo
  ports:
    - 27017:27017
  expose:
    - 27017
  container_name: mongo

mongo2:
  image: mongo
  ports:
    - 27027:27017
  expose:
    - 27027
  container_name: mongo2

redis:
  image: redis
  ports:
    - 6379:6379
  expose:
    - 6379
  container_name: redis
